/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author MMMM
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFundo = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlImagem = new javax.swing.JLabel();
        jSeparador = new javax.swing.JSeparator();
        jMenu = new javax.swing.JMenuBar();
        jmUsuario = new javax.swing.JMenu();
        jmCadastrarCliente = new javax.swing.JMenuItem();
        jmCadastrarFuncionario = new javax.swing.JMenuItem();
        jmUsuario1 = new javax.swing.JMenu();
        jmPlanodeTreino = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jFundo.setBackground(new java.awt.Color(153, 204, 255));

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jlTitulo.setText("ACADEMIA STAR");

        jlImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenicon/treinamento.png"))); // NOI18N

        javax.swing.GroupLayout jFundoLayout = new javax.swing.GroupLayout(jFundo);
        jFundo.setLayout(jFundoLayout);
        jFundoLayout.setHorizontalGroup(
            jFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFundoLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
            .addComponent(jSeparador)
            .addGroup(jFundoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFundoLayout.setVerticalGroup(
            jFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFundoLayout.createSequentialGroup()
                .addComponent(jlTitulo)
                .addGap(11, 11, 11)
                .addComponent(jSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        jmUsuario.setText("Gerenciar Usuario");

        jmCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/fitness-on-line.png"))); // NOI18N
        jmCadastrarCliente.setText("Cadastrar Cliente");
        jmCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarClienteActionPerformed(evt);
            }
        });
        jmUsuario.add(jmCadastrarCliente);

        jmCadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/fitness-on-line.png"))); // NOI18N
        jmCadastrarFuncionario.setText("Cadastrar Funcionario");
        jmCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jmUsuario.add(jmCadastrarFuncionario);

        jMenu.add(jmUsuario);

        jmUsuario1.setText("Gerenciar Plano de treino");

        jmPlanodeTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/fitness-on-line.png"))); // NOI18N
        jmPlanodeTreino.setText("Plano de treino");
        jmPlanodeTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPlanodeTreinoActionPerformed(evt);
            }
        });
        jmUsuario1.add(jmPlanodeTreino);

        jMenu.add(jmUsuario1);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarClienteActionPerformed
        CadastrarCliente cadastro = new CadastrarCliente();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jmCadastrarClienteActionPerformed

    private void jmCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarFuncionarioActionPerformed
        CadastrarFuncionario cadastro = new CadastrarFuncionario();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jmCadastrarFuncionarioActionPerformed

    private void jmPlanodeTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPlanodeTreinoActionPerformed
        jfPlano cadastro = new jfPlano();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jmPlanodeTreinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jFundo;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JSeparator jSeparador;
    private javax.swing.JLabel jlImagem;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JMenuItem jmCadastrarCliente;
    private javax.swing.JMenuItem jmCadastrarFuncionario;
    private javax.swing.JMenuItem jmPlanodeTreino;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenu jmUsuario1;
    // End of variables declaration//GEN-END:variables
}
